name: docker_client
version: 1.0.0-dev.1
description: Docker Engine API client
homepage: https://github.com/mosheduminer/docker_client
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.15.7
